apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}-config-json
  labels:
    app: {{ template "cloudflare-ddns.name" . }}
    app.kubernetes.io/name: {{ template "cloudflare-ddns.name" . }}
    helm.sh/chart: {{ template "cloudflare-ddns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {
      "ipv4": {{ .Values.config.ipv4}},
      "ipv6": {{ .Values.config.ipv6}},
      "records": [
        {{- range $record := $.Values.config.records }}
          {
            "zoneId": "{{ $record.zoneId }}",
            "subdomain": "{{ $record.subdomain }}",
            "proxied": {{ $record.proxied }}
          }
        {{- end }}
      ]
    }

