{{- if .Values.config.apiToken -}}
{{- fail "Please set the API Token with the secrets.apiToken and not with config.apiToken value." -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}-config-json
  labels:
    app: {{ template "cloudflare-ddns.name" . }}
    app.kubernetes.io/name: {{ template "cloudflare-ddns.name" . }}
    helm.sh/chart: {{ template "cloudflare-ddns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
