apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}
  labels:
    app: {{ template "cloudflare-ddns.name" . }}
    app.kubernetes.io/name: {{ template "cloudflare-ddns.name" . }}
    helm.sh/chart: {{ template "cloudflare-ddns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "cloudflare-ddns.name" . }}
  policyTypes:
    - Ingress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/20
              - 192.168.0.0/16
      ports:
        - port: 53
        - port: 443
