apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}-config-json
  labels:
    app: {{ template "cloudflare-ddns.name" . }}
    chart: {{ template "cloudflare-ddns.chart" . }}
    release: {{ .Release.Name }}
data:
  config.json: |
    {
      {{- if .Values.config.ipv4 }}
      "ipv4Resolver": "{{ .Values.config.ipv4 }}",
      {{- end }}
      {{- if .Values.config.ipv6 }}
      "ipv6Resolver": "{{ .Values.config.ipv6 }}",
      {{- end }}
      {{- if .Values.config.apiKey }}
      "apiKey": "{{ .Values.config.apiKey}}",
      {{- end }}
      "dns": [
        {{- range $dns := $.Values.config.dns }}
          {
            "zoneId": "{{ $dns.zoneId }}",
            "domain": "{{ $dns.domain }}",
            "proxied": {{ $dns.proxied }}
          }
        {{- end }}
      ]
    }
 
