{{ if .Values.secrets.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudflare-ddns.fullname" . }}-api-token
type: Opaque
stringData:
  api-token: {{$.Values.secrets.apiToken}}
{{ end }}