name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.403'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Package
        run: make

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/cloudflare-ddns
          file: Dockerfile
          push: true
          build-args: |
            MINVERVERSIONOVERRIDE=${{ steps.get_version.outputs.VERSION }}
          tags: |
            nickvdyck/cloudflare-ddns:latest
            nickvdyck/cloudflare-ddns:${{ steps.get_version.outputs.VERSION }}

      - name: Push to feedz.io
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/cloudflare-ddns/nuget/index.json --skip-duplicate
        
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts
    # - name: Push to nuget
    #   run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
